// <auto-generated />
namespace NetAtlas2.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class alead : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alead));
        
        string IMigrationMetadata.Id
        {
            get { return "202203140818525_alead"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
